CREATE TABLE [dbo].[Town]
(
	[TownId] INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	[TownName] NVARCHAR (225) NOT NULL,
	[StateId] INT NOT NULL, 
    CONSTRAINT [FK_Town_State] FOREIGN KEY ([StateId]) REFERENCES [State]([StateId]) ON DELETE CASCADE ON UPDATE CASCADE
)
